# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            集虚斋
tagline:          'made by Jekyll (Hyde theme)'
description:      'Reading, Learning, Thinking'
url:              https://lzhang12.github.io
baseurl:

author:
  name:           'Li Zhang'
  url:            http://www.li-zhang.net

paginate:         5

# Custom vars
github:           [metadata]
repository:       lzhang12/lzhang12.github.io.git
google_analytics: UA—172926919-1

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
